#!/usr/bin/env python3
"""Build a synthetic panel whose second dimension is real by construction.

The engines disagree about the second dimension on real Chilean data. That
disagreement has two candidate explanations, and no comparison between engines
can separate them, because none of them knows the right answer:

  A. a genuinely two-dimensional record also collapses -> implementation defect
  B. only the real record collapses, the synthetic one does not
                                                 -> empirically weak second
                                                    dimension in the data

Deciding between A and B needs a panel whose second dimension is known to be
real. This builds one, so that "collapse" becomes measurable against a truth
rather than against another engine.

Design decisions, and why
-------------------------
* **Ideal points are drawn with comparable spread on both dimensions** and are
  NOT a one-dimensional configuration with noise, so a genuine 2-D answer exists.
* **Cutting planes are drawn with uniformly distributed normal directions**, so
  a substantial share of roll calls discriminate mainly on dimension 2.  A panel
  whose planes are all dim-1 aligned would be 2-D in the ideal points and 1-D in
  the information, which is the very confound being tested for.
* **Votes are generated by the estimator's own model** (deterministic utilities,
  normal errors, the same clamped probit), so a correct implementation must be
  able to recover the truth.  This is a recovery test, not a robustness test.
* **The seed is computed from the votes alone**, by a double-centred SVD of the
  agreement matrix, so it is identical for every engine and carries no knowledge
  of the truth.  W-NOMINATE is unavailable here and seeding from the truth would
  answer the wrong question.
* **Panel size matches a real Chilean legislatura** (155 legislators, 716 roll
  calls), so the comparison is like-for-like against the panel that motivated
  the question.

Writes an engine-ready input directory plus `truth_coordinates.csv`.

Invocations that produced the three published panels are in
`data/synthetic-2d/README.md`.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import norm

# Portable: this file lives in <repo>/reproduce/, so the repository root is
# its parent. Do NOT hardcode a machine path here -- this script is meant to run on
# a collaborator's checkout.
REPO = Path(__file__).resolve().parent.parent


def generate(n_leg=155, n_rc=716, w1=1.0, w2=0.5, beta=6.0, seed=20260821,
             dim2_share=0.5, missing_rate=0.06):
    rng = np.random.default_rng(seed)

    # --- truth: a genuinely 2-D configuration inside the unit disk ----------
    # Two loosely separated blocs on dim 1 (as in a real legislature) plus an
    # INDEPENDENT dim-2 axis of comparable spread. Independence is the point:
    # dim 2 must not be recoverable from dim 1.
    half = n_leg // 2
    d1 = np.concatenate([rng.normal(-0.45, 0.22, half),
                         rng.normal(+0.45, 0.22, n_leg - half)])
    d2 = rng.normal(0.0, 0.40, n_leg)
    X = np.column_stack([d1, d2])
    r = np.hypot(X[:, 0], X[:, 1])
    scale = np.where(r > 0.97, 0.97 / np.maximum(r, 1e-12), 1.0)
    X = X * scale[:, None]

    # --- roll calls: cutting planes with uniformly distributed orientation --
    # `dim2_share` of the planes are deliberately drawn to cut mainly along
    # dimension 2, so the panel genuinely carries dim-2 information.
    theta = rng.uniform(0, 2 * np.pi, n_rc)
    is_d2 = rng.random(n_rc) < dim2_share
    theta[is_d2] = rng.normal(np.pi / 2, 0.35, int(is_d2.sum()))
    normal = np.column_stack([np.cos(theta), np.sin(theta)])
    # midpoint placed along the normal so the split is not always 50/50
    offset = rng.normal(0.0, 0.35, n_rc)
    Z = normal * offset[:, None]
    spread_mag = rng.uniform(0.2, 0.9, n_rc)
    D = normal * spread_mag[:, None]

    # --- votes, from the estimator's own model ------------------------------
    w = np.array([w1, w2])
    Uy = np.zeros((n_leg, n_rc))
    Un = np.zeros((n_leg, n_rc))
    for k in range(2):
        dY = X[:, k:k + 1] - Z[None, :, k] + D[None, :, k]
        dN = X[:, k:k + 1] - Z[None, :, k] - D[None, :, k]
        Uy += -(w[k] ** 2) * dY ** 2
        Un += -(w[k] ** 2) * dN ** 2
    zs = beta * (np.exp(Uy) - np.exp(Un))
    p_yea = norm.cdf(np.clip(zs, -5.0, 5.0))
    V = np.where(rng.random((n_leg, n_rc)) < p_yea, 1, 6)
    V = np.where(rng.random((n_leg, n_rc)) < missing_rate, 9, V)

    # drop roll calls that fail the 2.5 % minority screen; the engines would
    # screen them anyway and an unscreened panel misstates the panel size
    yy = (V == 1).sum(0); nn = (V == 6).sum(0); tot = yy + nn
    marg = np.divide(np.minimum(yy, nn), tot, out=np.zeros(n_rc), where=tot > 0)
    keep = marg >= 0.025
    V, Z, D, is_d2 = V[:, keep], Z[keep], D[keep], is_d2[keep]
    return X, Z, D, V, is_d2


def votes_seed(V: np.ndarray):
    """Engine-independent 2-D start from the votes alone (a W-NOMINATE stand-in).

    Double-centred SVD of the yea/nay agreement matrix. Uses no knowledge of the
    truth, so it cannot flatter any engine.
    """
    A = np.where(V == 1, 1.0, np.where(V == 6, -1.0, np.nan))
    col = np.nanmean(A, axis=0, keepdims=True)
    A = np.where(np.isnan(A), col, A)
    A = A - A.mean(0, keepdims=True)
    A = A - A.mean(1, keepdims=True)
    U, S, _ = np.linalg.svd(A, full_matrices=False)
    Y = U[:, :2] * S[:2]
    Y = Y / np.abs(Y).max() * 0.85
    return Y


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO / "reproduce" / "_out" / "synthetic2d"))
    ap.add_argument("--w2", type=float, default=0.5)
    ap.add_argument("--dim2-share", type=float, default=0.5)
    ap.add_argument("--seed", type=int, default=20260821)
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    X, Z, D, V, is_d2 = generate(w2=args.w2, dim2_share=args.dim2_share, seed=args.seed)
    n_leg, n_rc = V.shape
    legs = np.arange(1, n_leg + 1)
    rcs = np.arange(1, n_rc + 1)

    pd.DataFrame(V, index=pd.Index(legs, name=" "), columns=rcs).to_csv(
        out / "votes_matrix_p1.csv")
    pd.DataFrame({"legislator_id": legs, "id": legs, "nombres": "", "partido": "",
                  "region": "", "distrito": ""}).to_csv(
        out / "legislator_metadata.csv", index=False)

    Y = votes_seed(V)
    pd.DataFrame({"coord1D": Y[:, 0], "coord2D": Y[:, 1],
                  "legislator_id": legs}).to_csv(
        out / "wnominate_coordinates.csv", index=False)

    pd.DataFrame({"legislator_id": legs, "true_d1": X[:, 0],
                  "true_d2": X[:, 1]}).to_csv(out / "truth_coordinates.csv", index=False)
    pd.DataFrame({"rollcall_id": np.arange(n_rc),
                  "true_midpoint1D": Z[:, 0], "true_midpoint2D": Z[:, 1],
                  "true_spread1D": D[:, 0], "true_spread2D": D[:, 1],
                  "dim2_oriented": is_d2}).to_csv(
        out / "truth_bill_parameters.csv", index=False)

    # honest description of what was built
    seed_r = [float(np.corrcoef(Y[:, k], X[:, k])[0, 1]) for k in range(2)]
    print(f"synthetic 2-D panel -> {out}")
    print(f"  {n_leg} legislators x {n_rc} roll calls (after the 2.5 % screen)")
    print(f"  truth sd: dim1 {X[:,0].std():.4f}  dim2 {X[:,1].std():.4f}   "
          f"ratio {X[:,1].std()/X[:,0].std():.4f}")
    print(f"  |corr(true d1, true d2)| = {abs(np.corrcoef(X[:,0],X[:,1])[0,1]):.4f} "
          f"(should be ~0: the dimensions are independent)")
    print(f"  dim-2 oriented roll calls: {int(is_d2.sum())} of {n_rc} "
          f"({100*is_d2.mean():.1f} %)")
    print(f"  generating w2 = {args.w2}, beta = 6.0")
    print(f"  SEED quality (votes-only, no truth): r(seed,truth) "
          f"dim1 {seed_r[0]:+.4f}  dim2 {seed_r[1]:+.4f}")
    print("  -> the votes-only seed already carries a CORRECT dim 2. That sharpens the")
    print("     test rather than weakening it: an engine that collapses dim 2 from a")
    print("     correct start, on data that genuinely has one, is defective by")
    print("     elimination. Preserving it here while collapsing on Chile would instead")
    print("     say the Chilean second dimension is weak.")


if __name__ == "__main__":
    main()
